### ISSUE TITLE
I want to port gst-plugin-cedar to gstreamer 1.0 version,but  it have little error.

### ISSUE THREAD

**Issue by zhang007z** [ebutera/gst-plugin-cedar#1]
at current , I already  amend to :
//---------------------------------------------------------------------------------------------------------------------------//
                gst_buffer_set_caps(outbuf, GST_PAD_CAPS(filter->srcpad));
        GST_BUFFER_TIMESTAMP(outbuf) = GST_BUFFER_TIMESTAMP(buf);
        return gst_pad_push (filter->srcpad, outbuf);
//---------------------------------------------------------------------------------------------------------------------------//
but  this code is report error when gst_buffer_set_caps  is compiled. this main reason is that there is not gst_buffer_set_caps function in  gstreamer 1.0  library.
 I want to the code port to gstreamer 1.0 with your. thank for your help.

**Comment by ebutera** [comment]
In gstreamer 1.0 they addded the [GstVideoEncoder base class](http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-libs/html/gst-plugins-base-libs-GstVideoEncoder.html), you should use it.
Have a look at the x264enc or vp8enc plugins source to see how to use it, i think there is some tutorial too.

**Comment by zhang007z** [comment]
why I use your gst-plugin-cedar.? beacause I use Allwinner A10 cpu  chip(website:http://www.allwinnertech.com/en/clq/processora/A10.html).this chip SOC system is sunxi architecture(website:http://linux-sunxi.org/Main_Page). its video decode/encode hardware use cedarX(website:http://linux-sunxi.org/CedarX/Encoder).   so  I think your gst-plugin-cedar is optimal choise for video encode. In addition I want to know that whether truely availability  your cracking cedar plugin for  linux-sunxi cedarX hardware ?  thanks for your help.

**Comment by ebutera** [comment]
Sorry i explained myself badly.

I was meaning that the optimal way to port my cedar plugin to gstreamer 1.0 is to use the GstVideoEncoder base class, in other words it should be done like the x264enc or vp8enc do (they use the GstVideoEncoder base class and extend on top of it).

**Comment by sandmen** [comment]
Is a update planned for a current gstreamer version?

**Comment by ebutera** [comment]
Unfortunately right now i have no free time to update it, i don't know if @zhang007z made some progress...
